[package]
name = "roon-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
roon-moo = { path = "../roon-moo" }
roon-sood = { path = "../roon-sood" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
anyhow = "1"
dirs-next = "2"
futures-util = "0.3"
roon-moo = { path = "../roon-moo" }
tokio-tungstenite = "0.26"
tracing-subscriber = { workspace = true }
